name: Portfolio deploy

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build
        run: |
          git config user.email "danji_ma90@hotmail.com"
          git config user.name "danji90"
          npm install && npm run deploy

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
